# Generated by Django 6.1.1 on 2026-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('Urgent', 'Urgent'), ('Stable', 'Stable')], default='Stable', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharge', 'Discharge')], default='active', max_length=10)),
                ('vitals', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
