# Generated by Django 6.1.1 on 2026-09-13 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_bp_patient_chief_complaint_patient_gcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gps_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='history_present_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_surgical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TransferReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason_specialist_care', models.BooleanField(default=False)),
                ('reason_icu_bed', models.BooleanField(default=False)),
                ('reason_surgery', models.BooleanField(default=False)),
                ('reason_advanced_imaging', models.BooleanField(default=False)),
                ('reason_higher_level_care', models.BooleanField(default=False)),
                ('reason_other', models.BooleanField(default=False)),
                ('other_reason_details', models.CharField(blank=True, max_length=255, null=True)),
                ('ambulance_number', models.CharField(blank=True, max_length=50, null=True)),
                ('accompanying_staff', models.CharField(blank=True, max_length=150, null=True)),
                ('eta', models.CharField(blank=True, max_length=50, null=True)),
                ('oxygen', models.BooleanField(default=False)),
                ('ventilator', models.BooleanField(default=False)),
                ('monitor', models.BooleanField(default=False)),
                ('receiving_hospital_name', models.CharField(blank=True, max_length=150, null=True)),
                ('receiving_department', models.CharField(blank=True, max_length=100, null=True)),
                ('receiving_consultant', models.CharField(blank=True, max_length=150, null=True)),
                ('receiving_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('referring_doctor_name', models.CharField(max_length=150)),
                ('referring_doctor_pmdc', models.CharField(blank=True, max_length=50, null=True)),
                ('referring_doctor_designation', models.CharField(max_length=100)),
                ('referring_doctor_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('consent_details', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('received_at_destination', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.patient')),
            ],
        ),
    ]
