# Generated by Django 6.1.1 on 2026-10-05 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_patient_chief_complaint_remove_patient_vitals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientattachment',
            name='category',
            field=models.CharField(choices=[('lab_reports', 'Lab Reports'), ('radiology', 'Radiology Images'), ('medical_records', 'Medical Records'), ('prescription', 'Prescription'), ('referral_letter', 'Referral Letter'), ('clinical_photos', 'Clinical Photos'), ('investigation', 'Investigation')], max_length=30),
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_general', models.TextField(blank=True, null=True)),
                ('pe_cardiovascular', models.TextField(blank=True, null=True)),
                ('pe_respiratory', models.TextField(blank=True, null=True)),
                ('pe_abdomen', models.TextField(blank=True, null=True)),
                ('pe_neurological', models.TextField(blank=True, null=True)),
                ('pe_others', models.TextField(blank=True, null=True)),
                ('co_blood_pressure', models.BooleanField(default=False)),
                ('co_hepatitis_bc', models.BooleanField(default=False)),
                ('co_heart_disease', models.BooleanField(default=False)),
                ('co_asthma', models.BooleanField(default=False)),
                ('co_diabetes', models.BooleanField(default=False)),
                ('co_renal_liver_disease', models.BooleanField(default=False)),
                ('co_stroke', models.BooleanField(default=False)),
                ('co_cancer', models.BooleanField(default=False)),
                ('comorbidity_notes', models.TextField(blank=True, null=True)),
                ('working_diagnosis', models.CharField(max_length=255)),
                ('differential_diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('tr_iv_line', models.BooleanField(default=False)),
                ('tr_oxygen', models.BooleanField(default=False)),
                ('tr_blood_products', models.BooleanField(default=False)),
                ('tr_medications_administered', models.TextField(blank=True, null=True)),
                ('tr_procedure_performed', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='core.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='ClinicalNote',
        ),
    ]
