# Generated by Django 6.1.1 on 2026-10-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferreceipt',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='transferreceipt',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
